GET http://localhost:8080/orders
Content-Type: application/json

{
  "source": "Web",
  "orders": [
    {
      "id": "Order1",
      "status": "In Progress"
    },
    {
      "id": "Order2",
      "status": "In Progress"
    },
    {
      "id": "Order3",
      "status": "In Progress"
    }
  ]
}